# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"
os: Visual Studio 2017

clone_folder: C:\projects\omplapp
shallow_clone: true
platform: x64

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE="C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  CMAKE_GENERATOR: -G"Visual Studio 15 2017 Win64"
  VCPKG_ARCH: x64-windows

cache:
  - C:\tools\vcpkg\installed -> .appveyor.yml

configuration: Release

before_build:
  - cmd: vcpkg install boost:%VCPKG_ARCH%
  - cmd: vcpkg install eigen3:%VCPKG_ARCH%
  - cmd: vcpkg install fcl:%VCPKG_ARCH%
  - cmd: vcpkg install assimp:%VCPKG_ARCH%
  #- cmd: vcpkg install ode:%VCPKG_ARCH%
  - cmd: git clone -q --depth=1 --branch=master https://github.com/ompl/ompl.git C:\projects\omplapp\ompl
  - cmd: set
  - cmd: cd CMakeModules
  - cmd: del FindAssimp.cmake FindCCD.cmake FindFCL.cmake
  - cmd: cd ..
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%configuration% %CMAKE_TOOLCHAIN_FILE% -DOMPL_REGISTRATION=OFF ..

build:
  project: C:\projects\omplapp\build\omplapp.sln
  parallel: true

after_build:
  - cmd: cmake --build . --target package --config %Configuration%

test_script:
  - cmd: ctest -C %Configuration%

artifacts:
  - path: 'build\ompl*.zip'
